# Generated by Django 6.1 on 2026-09-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.TextField()),
                ('description', models.TextField(max_length=255)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
